name: spotify
description: "A new Flutter project."
publish_to: 'none' # لمنع نشر الحزمة على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.3.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  # Fonts
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 300
    